import React from 'react';
import '../styles/Home.css';

/* eslint-disable */
export default function Home() {
  return (
    <div className="home-container">
      <h4>WELCOME TO OUR PAGE !</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ac imperdiet nulla, sed bibendum erosc . Fusce in pellentesque arcu. Donec ut leo augue. Fusce eget pretium sem, semper suscipit ex. Vivamus facilisis et ante id viverra. Nulla ut dictum mauris. Pellentesque dignissim dui nec urna placerat, non egestas dui fermentum. In sollicitudin tincidunt leo a finibus. In luctus ultricies elit, quis luctus mauris molestie nec. Sed a molestie enim.Morbi dignissim quam eget quam congue porttitor rhoncus vel purus. Donec ac turpis ut erat ullamcorper vehicula. Nam in dui nisl. Aliquam aliquam ultrices ante id egestas. Maecenas elementum lorem diam, et tincidunt velit finibus eu. Nullam sollicitudin tempor leo, eu pharetra erat vulputate a. Maecenas mollis neque aliquam justo iaculis laoreet. Aliquam venenatis pretium lacinia. In nec sollicitudin metus. In iaculis luctus sem sed aliquam. Ut id sagittis nunc.Proin ac molestie mauris. Phasellus et accumsan massa, vel tincidunt tortor. Sed at lobortis lorem. Donec metus ligula, vestibulum sit amet finibus id, hendrerit a ex. Integer in elit maximus, accumsan turpis ultricies, suscipit orci. Praesent molestie mattis metus, sed volutpat nisi luctus eget. Praesent quis ullamcorper neque. Nunc egestas, enim in consequat fermentum, leo libero mattis neque, sed sagittis libero augue in tortor. Donec consectetur et arcu consequat facilisis. Vestibulum quis interdum sem, ut convallis elit.Aliquam ut nunc mattis, vulputate lorem vitae, rutrum arcu. Nunc eget diam sit amet dui pulvinar luctus in vel libero. Vivamus tempus lorem nulla, sit amet facilisis libero hendrerit a. Integer ut odio vel est feugiat scelerisque sed sed felis. Nam urna sapien, euismod a faucibus sed, finibus elementum nibh. In hac habitasse platea dictumst. Curabitur eu eros quis sem tincidunt feugiat nec a ante. Aliquam interdum congue metus, eu auctor justo euismod id. Quisque vel risus consectetur, mattis lorem a, tincidunt est. Aenean ut efficitur odio. Pellentesque justo mi, convallis vitae tincidunt id, congue id turpis. Integer eu tristique ante. Fusce mollis tellus quis ipsum efficitur, vitae rutrum turpis commodo. Nullam vitae blandit tellus.In eu scelerisque elit, ut rutrum leo. Sed eu neque ut dolor fermentum iaculis. Mauris vehicula leo vitae mauris maximus, vitae hendrerit nisi mattis. Integer ullamcorper arcu eu imperdiet viverra. Ut vel erat scelerisque ante molestie semper consequat eu ipsum. Nullam lacus sapien, varius quis libero ut, porta euismod dui. Etiam scelerisque neque aliquam ligula efficitur, quis fermentum ante interdum. Aenean consectetur est mi, non ullamcorper massa iaculis quis. Aliquam lobortis ligula nec ligula sollicitudin</p>
    </div>
  );
}
